(#1952) Fix fact filter parsing
choria-io/go-choria pull request #1954
Opened 2023-01-09 10:30 UTC by ploubser

With the addition of GJson to describe fact values the old fact parser is no longer able to correctly identify facts vs operators in examples like `'storage.#(name=="vda").size'`.

Here we rewrite the ParseFactFilterString function to no longer used complicated regular expressions. We will now correctly identify GJson facts and parse the filters correctly.

In addition we're adding a wider range of tests for ParseFactFilterString so that we're covered if we were to add more fact filter functionality in the future.

2023-01-09 11:10 UTC, ripienaar requested changes
looking pretty good, minor comments

2023-01-09 15:42 UTC, ripienaar commented on filter/facts/facts_test.go
> +	Describe("ParseFactFilterString", func() {
Ah these https://github.com/choria-io/go-choria/blob/89da56f2d1fa15a1bc8aa8bbb096940ac32dd8fa/filter/filter_test.go#L99

Lets combine them so the function is tested one place only

2023-01-09 16:06 UTC, ploubser commented on filter/facts/facts.go
> +	f = strings.ReplaceAll(f, " ", "")
So this happens before we identify any of the 3 tokens that make up a valid fact filter. I agree that using Trimspace() is a more elegant solution to removing the whitespace, but we would have to call it on both the left and right operands later in the function. Trimspace also might fall apart if this is a valid fact filter

```
storage.#(name == "vda").size = 64
```

2023-01-09 16:07 UTC, ploubser commented on filter/facts/facts.go
> +	validOperators := regexp.MustCompile(`<=|>=|=>|=<|<|>|!=|=~|={1,2}`)
👍

2023-01-09 16:07 UTC, ploubser commented on filter/facts/facts_test.go
> +	Describe("ParseFactFilterString", func() {
👍

2023-01-09 16:11 UTC, ripienaar commented on filter/facts/facts.go
> +	f = strings.ReplaceAll(f, " ", "")
Ah, I see, but we also cant just remove all the whitespace though can we? What If I want to match against `"Foo Bar"` wont that turn it into `"FooBar"`?

2023-01-09 16:21 UTC, ploubser commented on filter/facts/facts.go
> +	f = strings.ReplaceAll(f, " ", "")
Yep, that's correct. Let me rethink this.

2023-01-10 10:03 UTC, ripienaar commented on filter/filter_test.go
> +		It("Should fail on invalid fact filters", func() {
looks great, lets add a few tests against these new kinds of filters that would have triggered the bug and this one is done!

2023-01-10 10:28 UTC, ripienaar commented on filter/filter_test.go
> +			t("storage.#(name=\"foo bar\").size=>baz bar", "storage.#(name=\"foo bar\").size", ">=", "baz bar")
Also works with single quotes like `storage.#(name=\"nvme0n1\").size=64`?

last one I think :)

2023-01-10 10:57 UTC, ripienaar approved these changes
LGTM!

2023-01-10 11:08 UTC, merged